default: &default
  adapter: postgresql
  encoding: unicode
  username: eriko
  password: eriko
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: invitation_development
  username: eriko
  password: eriko

test:
  <<: *default
  database: invitation_test

production:
  <<: *default
  database: invitation_production
  username: myapp
  password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>
